apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector
  namespace: appns
  labels:
    app: connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connector
  template:
    metadata:
      labels:
        app: connector
    spec:
      containers:
        - name: connector
          image: connector   # <-- replace alikhalid15
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: connector-config
            - secretRef:
                name: connector-secret
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: "500m"
              memory: "64Mi"
            limits:
              cpu: "2500m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: connector-svc
  namespace: appns
spec:
  selector:
    app: connector
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer 
